title: DotNetDevs.at
email: info@dotnetdevs.at
description: >-
  Monthly .NET events to spread knowledge and experience.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dotnetdevs.at" # the base hostname & protocol for your site
locale: "en"
theme: "minimal-mistakes-jekyll"
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-archives
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-collections

# Minimal Mistakes settings
minimal_mistakes_skin: "default"
search: false

# Collections for events and speakers
collections:
  events:
    output: true
    permalink: /events/:path/
    sort_by: date
    sort_order: desc
  speakers:
    output: true
    permalink: /speakers/:path/
  sponsors:
    output: true
    permalink: /sponsors/:path/

defaults:
  # _sponsors
  - scope:
      path: ""
      type: sponsors
    values:
      layout: single
      author_profile: false
      share: false
  # events
  - scope:
      path: ""
      type: events
    values:
      layout: event
      author_profile: false
      share: true
  # speakers
  - scope:
      path: ""
      type: speakers
    values:
      layout: single
      author_profile: false
      share: false


# Analytics (Plausible)
# Add plausible script in _includes/head-custom.html

footer:
  links:

atom_feed:
  hide: true